### ISSUE TITLE
customView should not block content from working.

### ISSUE THREAD

**Issue by GraxCode** [maxkeppeler/sheets#95]
When I use customView(), content() text does not display anymore.

**Comment by maxkeppeler** [comment]
The provided Infosheet texts are gone as you replace it with a custom view. Either use a custom view or the default InfoSheet with its look/ TextViews. It behaves as it should.

**Comment by GraxCode** [comment]
Do drawables behave the same way? As far as I know, they don't seem to: https://github.com/maxkeppeler/sheets/blob/main/art/InfoSheet%20Dialog%20Cover%20TopStyle%20Top.png
I intended to use the custom view as a view for an item in my game, while above it there is a description.
Of course, i could add a TextView, but as InfoSheet already has a content() method I don't really understand this design choice.

**Comment by maxkeppeler** [comment]
No. The drawables and the image are views that are within the cover view, which is displayed above the content view of the sheet. If you add them, they are displayed, otherwise not. With contentView you can replace the content, where normally the info drawable, info text and so on is placed. If you want to use those standard components, don't replace the view. If you have specific needs, you can just build upon a Sheet and build your own.
